const slugify = require("slugify");

console.log(`// File generated by ${process.argv[1]}`);
console.log(`// Do not edit.\n`);

console.log("let shaders = [];\n");

const shaderNamesAndTitles = [
  ["grid_lines4", "grid lines 3"],
  ["grid_lines3", "grid lines 2"],
  ["grid_lines2", "grid lines"],
  ["fireworks", "fireworks"],
  ["flower2", "flower 2"],
  ["flower", "flower"],
  ["dots", "dots"],
  ["clouds", "clouds"],
  ["rain", "rain"],
  ["ray_march_drip", "drip"],
  ["refract", "refract"],
  ["ray_march", "ray march"],
  ["cells", "cells"],
  ["fabric", "fabric"],
  ["directional_lighting", "directional lighting"],
  ["projectile", "projectiles"],
];

shaderNamesAndTitles.forEach(function([name, title]) {
  const filename = `../shaders/${name}.glsl`;

  console.log(`import ${name} from "${filename}";`);
  console.log(`import ${name}_raw from "!raw-loader!${filename}";`);
  console.log(`shaders.push({
    source: ${name},
    raw_source: ${name}_raw,
    title: "${title}",
    slug: "${slugify(title)}",
  });\n`);
});

console.log("export default shaders;");
